name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # 添加这行

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Initialize Prisma and SQLite
      run: |
        npx prisma generate
        npx prisma db push --accept-data-loss 

    - name: Build project
      run: npm run build
      env:
        DATABASE_URL: "file:./dev.db"
        NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
